version: "3"
services:
  db:
    image: postgres
    ports:
      - "5433:5432"
  web:
    build: .
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes: ['./src:/app/src']
    env_file:
      - .env
