from python:3.7.1-alpine3.8

WORKDIR /app
# optimize pip dependencies
ADD ./requirements /app/requirements
RUN pip install -r /app/requirements/prod.txt

COPY . /app

EXPOSE 8000

CMD ["gunicorn", "src.gunicorn:app", "--bind", "0.0.0.0:8000", \
"--worker-class", "aiohttp.GunicornWebWorker"]
