version: "3"
services:
  nginx:
    image: abiosoft/caddy
    container_name: caddy_prod
    volumes:
      - ./config/Caddyfile:/etc/Caddyfile
      - ./static:/srv/static
    ports:
      - 80:80
      - 443:443
      - 2015:2015
    depends_on:
      - web
    networks:
      - web_nw

  web:
    image: schedulebot_prod
    env_file:
      - .env
    networks:
      - web_nw

networks:
  web_nw:
    driver: bridge
