version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/srv/static
    ports:
      - 80:80
      - 443:443
    networks:
      - web_nw

  web:
    image: schedulebot_prod
    env_file:
      - .env
    networks:
      - web_nw

networks:
  web_nw:
    driver: bridge
