version: "3"
services:
  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443
    networks:
      - web_nw

  web:
    build: .
    ports:
      - 8000:8000
      - 8001:8001
    env_file:
      - .env
    networks:
      - web_nw

networks:
  web_nw:
    driver: bridge
