version: "3"
services:
  nginx:
    image: nginx
    container_name: caddy_prod
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/srv/static
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    networks:
      - web_nw

  web:
    image: schedulebot_prod
    env_file:
      - .env
    networks:
      - web_nw

networks:
  web_nw:
    driver: bridge
