version: "3"
services:
  database:
    image: postgres
    container_name: database_prod
    networks:
      - database_nw
    env_file:
      - .env

  web:
    image: schedulebot_prod
    env_file:
      - .env
    networks:
      - web_nw
      - database_nw
    depends_on:
      - database
    entrypoint:
      - gunicorn
      - src.gunicorn:app
      - -c
      - config/gunicorn.py

  caddy:
    image: abiosoft/caddy
    container_name: caddy_prod
    volumes:
      - ./config/Caddyfile:/etc/Caddyfile
      - ./static:/srv/static
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    networks:
      - web_nw

networks:
  web_nw:
    driver: bridge
  database_nw:
    driver: bridge
