version: "3"
services:
  nginx:
    image: nginx
    container_name: nginx_prod
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf
      - ./static:/srv/static
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
    networks:
      - web_nw
    entrypoint: "/bin/sh -c 'while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g \"daemon off;\"'"

  certbot:
    image: certbot/certbot
    volumes:
      - ./data/certbot/conf:/etc/letsencrypt
      - ./data/certbot/www:/var/www/certbot
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

  web:
    image: schedulebot_prod
    env_file:
      - .env
    networks:
      - web_nw
    entrypoint:
      - gunicorn
      - src.gunicorn:app
      - -c
      - config/gunicorn.py

networks:
  web_nw:
    driver: bridge
